sudo: false

services:
  - mongodb

language: go

go:
  - 1.7
  - 1.8

install:
  - cd $TRAVIS_BUILD_DIR/..

before_script:

script:
  - echo "$TRAVIS_BRANCH"@"$TRAVIS_COMMIT"
  - cd $TRAVIS_BUILD_DIR && source env.sh travis && make travis
