sudo: false

services:
  - mongodb

language: go

go:
  - 1.7
  - 1.8

install:
  - mkdir -p $TRAVIS_BUILD_DIR/gopkg
  - export GOPATH=$TRAVIS_BUILD_DIR/gopkg:$GOPATH
  - export PATH=$TRAVIS_BUILD_DIR/gopkg/bin:$PATH

before_script:

script:
  - echo "$TRAVIS_BRANCH"@"$TRAVIS_COMMIT"
  - cd $TRAVIS_BUILD_DIR && source env.sh travis && make travis
